# This rule is not used by the project go-operator-sdk itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over cache.k8s.capitalontap.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: go-operator-sdk
    app.kubernetes.io/managed-by: kustomize
  name: samtest-admin-role
rules:
- apiGroups:
  - cache.k8s.capitalontap.com
  resources:
  - samtests
  verbs:
  - '*'
- apiGroups:
  - cache.k8s.capitalontap.com
  resources:
  - samtests/status
  verbs:
  - get
